package orm;

import hant.Log;
import hant.PathTools;
import haquery.server.db.HaqDb;
import FlashDevelopProject;

class OrmGenerator
{
	var log : Log;
	var project : FlashDevelopProject;
	
	public function new(log:Log, project:FlashDevelopProject)
    {
		this.log = log;
		this.project = project;
	}
	
	public function generate(db:HaqDb)
	{
		for (table in db.connection.getTables())
        {
			var className = getClassName(table);
			OrmModelGenerator.make(log, project, db, table, 'models.server.' + className, 'models.server.autogenerated.' + className, 'managers.server.' + className + 'Manager');
			OrmManagerGenerator.make(log, project, db, table, 'models.server.' + className, 'managers.server.' + className + 'Manager', 'managers.server.autogenerated.' + className + 'Manager');
        }
    }
	
	function getClassName(table:String) : String
    {
		var s = "";
		
		var packs = table.toLowerCase().split("__");
		while (packs.length > 1)
		{
			var pack = packs.shift();
			var words = pack.split("_");
			s += words.shift();
			s += Lambda.map(words, function(w) return OrmTools.capitalize(w)).join('');
			s += ".";
		}
		
		s += Lambda.map(packs[0].split("_"), function(w) return OrmTools.capitalize(w)).join('');
		
		return s;
    }
}
