<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>test2</title>
        {styles}
        {scripts}
    </head>
    <body>
        Page<br />
        <input type="button" id="mybt1" value="Press me 1!" /><br />
        <haq:button id="mybt2" text="Press me 2!" /><br />
        <div id="status"></div>
        
        <haq:ckeditor />
    </body>
</html>
