// This is autogenerated file. Do not edit!

package components.calculator.calc;

class TemplateClient
{
	var component : haquery.client.HaqComponent;
	
	public var calculator(calculator_getter, null) : haquery.client.HaqQuery;
	inline function calculator_getter() : haquery.client.HaqQuery
	{
		return component.q('#calculator');
	}
	
	public var history(history_getter, null) : haquery.client.HaqQuery;
	inline function history_getter() : haquery.client.HaqQuery
	{
		return component.q('#history');
	}
	
	public var memory(memory_getter, null) : haquery.client.HaqQuery;
	inline function memory_getter() : haquery.client.HaqQuery
	{
		return component.q('#memory');
	}
	
	public var number(number_getter, null) : haquery.client.HaqQuery;
	inline function number_getter() : haquery.client.HaqQuery
	{
		return component.q('#number');
	}
	
	public var bt_MC(bt_MC_getter, null) : components.calculator.button.Client;
	inline function bt_MC_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_MC');
	}
	
	public var bt_MR(bt_MR_getter, null) : components.calculator.button.Client;
	inline function bt_MR_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_MR');
	}
	
	public var bt_MS(bt_MS_getter, null) : components.calculator.button.Client;
	inline function bt_MS_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_MS');
	}
	
	public var bt_MP(bt_MP_getter, null) : components.calculator.button.Client;
	inline function bt_MP_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_MP');
	}
	
	public var bt_MM(bt_MM_getter, null) : components.calculator.button.Client;
	inline function bt_MM_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_MM');
	}
	
	public var bt_BS(bt_BS_getter, null) : components.calculator.button.Client;
	inline function bt_BS_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_BS');
	}
	
	public var bt_CE(bt_CE_getter, null) : components.calculator.button.Client;
	inline function bt_CE_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_CE');
	}
	
	public var bt_C(bt_C_getter, null) : components.calculator.button.Client;
	inline function bt_C_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_C');
	}
	
	public var bt_SIGN(bt_SIGN_getter, null) : components.calculator.button.Client;
	inline function bt_SIGN_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_SIGN');
	}
	
	public var bt_SQRT(bt_SQRT_getter, null) : components.calculator.button.Client;
	inline function bt_SQRT_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_SQRT');
	}
	
	public var bt_7(bt_7_getter, null) : components.calculator.button.Client;
	inline function bt_7_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_7');
	}
	
	public var bt_8(bt_8_getter, null) : components.calculator.button.Client;
	inline function bt_8_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_8');
	}
	
	public var bt_9(bt_9_getter, null) : components.calculator.button.Client;
	inline function bt_9_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_9');
	}
	
	public var bt_DIV(bt_DIV_getter, null) : components.calculator.button.Client;
	inline function bt_DIV_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_DIV');
	}
	
	public var bt_PERCENT(bt_PERCENT_getter, null) : components.calculator.button.Client;
	inline function bt_PERCENT_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_PERCENT');
	}
	
	public var bt_4(bt_4_getter, null) : components.calculator.button.Client;
	inline function bt_4_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_4');
	}
	
	public var bt_5(bt_5_getter, null) : components.calculator.button.Client;
	inline function bt_5_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_5');
	}
	
	public var bt_6(bt_6_getter, null) : components.calculator.button.Client;
	inline function bt_6_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_6');
	}
	
	public var bt_MUL(bt_MUL_getter, null) : components.calculator.button.Client;
	inline function bt_MUL_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_MUL');
	}
	
	public var bt_OBR(bt_OBR_getter, null) : components.calculator.button.Client;
	inline function bt_OBR_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_OBR');
	}
	
	public var bt_1(bt_1_getter, null) : components.calculator.button.Client;
	inline function bt_1_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_1');
	}
	
	public var bt_2(bt_2_getter, null) : components.calculator.button.Client;
	inline function bt_2_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_2');
	}
	
	public var bt_3(bt_3_getter, null) : components.calculator.button.Client;
	inline function bt_3_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_3');
	}
	
	public var bt_SUB(bt_SUB_getter, null) : components.calculator.button.Client;
	inline function bt_SUB_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_SUB');
	}
	
	public var bt_0(bt_0_getter, null) : components.calculator.button.Client;
	inline function bt_0_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_0');
	}
	
	public var bt_POINT(bt_POINT_getter, null) : components.calculator.button.Client;
	inline function bt_POINT_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_POINT');
	}
	
	public var bt_ADD(bt_ADD_getter, null) : components.calculator.button.Client;
	inline function bt_ADD_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_ADD');
	}
	
	public var bt_EQU(bt_EQU_getter, null) : components.calculator.button.Client;
	inline function bt_EQU_getter() : components.calculator.button.Client
	{
		return cast component.components.get('bt_EQU');
	}

	public function new(component:haquery.client.HaqComponent) : Void
	{
		this.component = component;
	}
}
