// This is autogenerated file. Do not edit!

package components.buttonexample;

class Template
{
	var component : #if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end;
	
	public var status(status_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function status_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#status');
	}

	public function new(component:#if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end) : Void
	{
		this.component = component;
	}
}