// This is autogenerated file. Do not edit!

package components.set1.randnum;

class Template
{
	var component : #if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end;
	
	public var n(n_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function n_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#n');
	}

	public function new(component:#if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end) : Void
	{
		this.component = component;
	}
}