package models.server;

#if server

/**
 * Special class for access to ORM (instance is 'db.orm').
 */
class Orm extends models.server.autogenerated.Orm
{
	// additional vars here

	public function new(db:haquery.server.db.HaqDb)
	{
		super(db);
		
		// add vars initialization here
	}
}

#end