// This is autogenerated file. Do not edit!

package pages.index;

class TemplateServer
{
	var component : haquery.server.HaqComponent;
	
	public var pagebt(pagebt_getter, null) : components.haquery.button.Server;
	inline function pagebt_getter() : components.haquery.button.Server
	{
		return cast component.components.get('pagebt');
	}
	
	public var pagesbt(pagesbt_getter, null) : haquery.server.HaqQuery;
	inline function pagesbt_getter() : haquery.server.HaqQuery
	{
		return component.q('#pagesbt');
	}
	
	public var users(users_getter, null) : components.haquery.list.Server;
	inline function users_getter() : components.haquery.list.Server
	{
		return cast component.components.get('users');
	}
	
	public var status(status_getter, null) : haquery.server.HaqQuery;
	inline function status_getter() : haquery.server.HaqQuery
	{
		return component.q('#status');
	}

	public function new(component:haquery.server.HaqComponent) : Void
	{
		this.component = component;
	}
}
