// This is autogenerated file. Do not edit!

package pages.index;

class Template
{
	var component : #if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end;
	
	public var pagebt(pagebt_getter, null) : #if php haquery.components.button.Server #else haquery.components.button.Client #end;
	inline function pagebt_getter() : #if php haquery.components.button.Server #else haquery.components.button.Client #end
	{
		return cast component.components.get('pagebt');
	}
	
	public var pagesbt(pagesbt_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function pagesbt_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#pagesbt');
	}
	
	public var users(users_getter, null) : #if php haquery.components.list.Server #else haquery.components.list.Client #end;
	inline function users_getter() : #if php haquery.components.list.Server #else haquery.components.list.Client #end
	{
		return cast component.components.get('users');
	}
	
	public var status(status_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function status_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#status');
	}

	public function new(component:#if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end) : Void
	{
		this.component = component;
	}
}