// This is autogenerated file. Do not edit!

package components.calculator.joke;

class TemplateServer
{
	var component : haquery.server.HaqComponent;
	
	public var joke(joke_getter, null) : haquery.server.HaqQuery;
	inline function joke_getter() : haquery.server.HaqQuery
	{
		return component.q('#joke');
	}
	
	public var text(text_getter, null) : haquery.server.HaqQuery;
	inline function text_getter() : haquery.server.HaqQuery
	{
		return component.q('#text');
	}

	public function new(component:haquery.server.HaqComponent) : Void
	{
		this.component = component;
	}
}
