// This is autogenerated file. Do not edit!

package pages.index;

class Template
{
	var component : #if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end;
	
	public var simpleButton(simpleButton_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function simpleButton_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#simpleButton');
	}
	
	public var componentButton(componentButton_getter, null) : #if php haquery.components.button.Server #else haquery.components.button.Client #end;
	inline function componentButton_getter() : #if php haquery.components.button.Server #else haquery.components.button.Client #end
	{
		return cast component.components.get('componentButton');
	}
	
	public var status(status_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function status_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#status');
	}

	public function new(component:#if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end) : Void
	{
		this.component = component;
	}
}