package ;

//import php.db.ResultSet;
import php.FileSystem;
import php.io.File;
import php.io.FileOutput;
import php.Lib;
import haquery.server.db.HaqDb;
import haquery.server.db.HaqDbDriver;
import OrmHaxeClass;

class OrmModelGenerator 
{
	static public function make(table:String, basePath:String, customModelFullClassName:String, autoGenModelFullClassName:String) : Void
	{
		basePath = basePath.replace('\\', '/').rtrim('/') + '/';
		
		Lib.println("");
		Lib.println(table + " => " + customModelFullClassName);
		
		var vars = OrmTools.fields2vars(HaqDb.connection.getFields(table));
		
		var autoGeneratedModel = getAutoGeneratedModel(table, vars, autoGenModelFullClassName);
		File.putContent(basePath + autoGenModelFullClassName.replace('.', '/') + '.hx', autoGeneratedModel.toString());
		
		var customModel = getCustomModel(table, vars, customModelFullClassName, autoGenModelFullClassName);
		var pathToCustomModel = basePath + customModelFullClassName.replace('.', '/') + '.hx';
		if (!FileSystem.exists(pathToCustomModel)) 
		{
			File.putContent(pathToCustomModel, customModel.toString());
		}
	}
	
	static function getAutoGeneratedModel(table:String, vars:List<OrmHaxeVar>, fullClassName:String, baseFullClassName:String=null) : OrmHaxeClass
	{
		var model:OrmHaxeClass = new OrmHaxeClass(fullClassName, baseFullClassName);
		
		model.addImport('haquery.server.db.HaqDb');
		
		for (v in vars)
		{
			model.addVar(v);
		}
		
        model.addMethod('new', [], 'Void', '');
        
        if (Lambda.exists(vars, function(v:OrmHaxeVar) { return v.isKey; } ) && Lambda.exists(vars, function(v:OrmHaxeVar) { return !v.isKey; } ))
		{
			var settedVars = Lambda.filter(vars, function(v:OrmHaxeVar) { return !v.isKey && !v.isAutoInc; } );
			if (settedVars.length > 0)
			{
				model.addMethod('set', settedVars, 'Void',
					Lambda.map(settedVars, function(v:OrmHaxeVar) { return 'this.' + v.haxeName + " = " + v.haxeName + ";"; }).join('\n')
				);
			}
			
			var savedVars = Lambda.filter(vars, function(v:OrmHaxeVar) { return !v.isKey; } );
			var whereVars = Lambda.filter(vars, function(v:OrmHaxeVar) { return v.isKey; } );
			model.addMethod('save', new List<OrmHaxeVar>(), 'Void',
				 "HaqDb.query(\n"
				    +"\t 'UPDATE `" + table + "` SET '\n"
					+"\t\t+  '" + Lambda.map(savedVars, function(v:OrmHaxeVar) { return "`" + v.name + "` = ' + HaqDb.quote(" + v.haxeName + ")"; }).join("\n\t\t+', ")
					+"\n\t+' WHERE " 
					+Lambda.map(whereVars, function(v:OrmHaxeVar) { return "`" + v.name + "` = ' + HaqDb.quote(" + v.haxeName + ")"; } ).join("+' AND ")
					+"\n\t+' LIMIT 1'"
				+"\n);"
			);
		}
		
		return model;
	}

	static function getCustomModel(table:String, vars:List<OrmHaxeVar>, fullClassName:String, baseFullClassName:String=null) : OrmHaxeClass
	{
		var model:OrmHaxeClass = new OrmHaxeClass(fullClassName, baseFullClassName);
		var clas = OrmTools.splitFullClassName(fullClassName);
		
		model.addImport('haquery.server.db.HaqDb');
		model.addImport(clas.packageName + '.' + clas.className + 'Manager');
		
		model.addVar(OrmTools.createVar('manager', clas.className + 'Manager', 'new ' + clas.className + 'Manager()'), false, true);
		
		return model;
	}
}