// This is autogenerated file. Do not edit!

package components.joke;

class Template
{
	var component : #if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end;
	
	public var joke(joke_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function joke_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#joke');
	}
	
	public var text(text_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function text_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#text');
	}

	public function new(component:#if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end) : Void
	{
		this.component = component;
	}
}