<?php include "support/layout.phtml" ?>

<syq:content id="content">
    <div class="panReklama">
        <p>Старый знакомый для простых вычислений.</p>
        <p>Быстро, удобно, надёжно, да к тому же онлайн.</p>
        <p>Если вдруг что-то пойдёт не так - смело пишите на e-mail.</p>
        <p>Пусть вам почаще нужно будет подсчитывать свои доходы!</p>
        <p>Удачи!</p>
    </div>

    <div class="panCalculator">
        <syq:calculator id="calc" />
    </div>

    <div class="panJoke">
        <div style="height: 130px">
            <syq:joke />
        </div>

        <div class="panHistory">
            <span class="h2">История вычислений</span>
            <textarea id="history" readonly="readonly"></textarea>
        </div>
    </div>

    <div class="clearfix">&nbsp;</div>
</syq:content>
