// This is autogenerated file. Do not edit!

package pages.index;

class TemplateClient
{
	var component : haquery.client.HaqComponent;
	
	public var mainShadow(mainShadow_getter, null) : haquery.client.HaqQuery;
	inline function mainShadow_getter() : haquery.client.HaqQuery
	{
		return component.q('#mainShadow');
	}
	
	public var calc(calc_getter, null) : components.calculator.calc.Client;
	inline function calc_getter() : components.calculator.calc.Client
	{
		return cast component.components.get('calc');
	}
	
	public var history(history_getter, null) : haquery.client.HaqQuery;
	inline function history_getter() : haquery.client.HaqQuery
	{
		return component.q('#history');
	}

	public function new(component:haquery.client.HaqComponent) : Void
	{
		this.component = component;
	}
}
