// This is autogenerated file. Do not edit!

package pages.index;

class Template
{
	var component : #if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end;
	
	public var mainShadow(mainShadow_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function mainShadow_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#mainShadow');
	}
	
	public var calc(calc_getter, null) : #if php haquery.server.HaqComponent #else components.calculator.Client #end;
	inline function calc_getter() : #if php haquery.server.HaqComponent #else components.calculator.Client #end
	{
		return cast component.components.get('calc');
	}
	
	public var history(history_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function history_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#history');
	}

	public function new(component:#if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end) : Void
	{
		this.component = component;
	}
}