// This is autogenerated file. Do not edit!

package components.set1.randnum;

class TemplateServer
{
	var component : haquery.server.HaqComponent;
	
	public var n(n_getter, null) : haquery.server.HaqQuery;
	inline function n_getter() : haquery.server.HaqQuery
	{
		return component.q('#n');
	}

	public function new(component:haquery.server.HaqComponent) : Void
	{
		this.component = component;
	}
}
