<style>
    .button
    {
        border-collapse: collapse;
        border: 0;
        padding: 0;
        cursor: pointer;
        background: url(~/bt_l.png) no-repeat;
        margin:auto;
    }

    .button td
    {
        text-align: center;
        background: url(~/bt_r.png) no-repeat top right;
        font-size: 13px;
        color: #888;
        line-height: 21px;
        height: 21px;
        padding: 0 8px !important;
    }

    .button.active td
    {
        color: #fff;
    }
</style>

<table id="b" class="button active"><tr><td>OK</td></tr></table>