package ;

import php.db.ResultSet;
import php.FileSystem;
import php.Lib;
import haquery.server.db.HaqDb;
import haquery.server.db.HaqDbDriver;
import OrmTools;
using haquery.StringTools;

class OrmGenerator
{
    static function getClassName(table:String) : String
    {
		return Lambda.map(table.toLowerCase().split('_'), function(w) { return OrmTools.capitalize(w); } ).join('');
    }

	static public function make(basePath:String)
    {
		basePath = basePath.replace('\\', '/').rtrim('/') + '/';
		
        var modelFolder = basePath + 'models/';
		if (!FileSystem.isDirectory(modelFolder))
		{
			FileSystem.createDirectory(modelFolder);
		}
        if (!FileSystem.isDirectory(modelFolder + 'autogenerated'))
		{
			FileSystem.createDirectory(modelFolder + 'autogenerated');
		}
        
        var managerFolder = basePath + 'managers/';
		if (!FileSystem.isDirectory(managerFolder))
		{
			FileSystem.createDirectory(managerFolder);
		}
        if (!FileSystem.isDirectory(managerFolder + 'autogenerated'))
		{
			FileSystem.createDirectory(managerFolder + 'autogenerated');
		}
        
		
        
        var tables = HaqDb.connection.getTables();
        for (table in tables)
        {
			var className = getClassName(table);
			OrmModelGenerator.make(table, basePath, 'models.' + className, 'models.autogenerated.' + className, 'managers.' + className + 'Manager');
			OrmManagerGenerator.make(table, basePath, 'models.' + className, 'managers.' + className + 'Manager', 'managers.autogenerated.' + className + 'Manager');
        }
    }
}
