// This is autogenerated file. Do not edit!

package components.mycomp;

class Template
{
	var component : #if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end;
	
	public var serverStatus(serverStatus_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function serverStatus_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#serverStatus');
	}
	
	public var clientStatus(clientStatus_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function clientStatus_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#clientStatus');
	}

	public function new(component:#if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end) : Void
	{
		this.component = component;
	}
}