// This is autogenerated file. Do not edit!

package components.comp;

class Template
{
	var component : #if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end;
	
	public var innerSimpleButton(innerSimpleButton_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function innerSimpleButton_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#innerSimpleButton');
	}
	
	public var innerComponentButton(innerComponentButton_getter, null) : #if php haquery.components.button.Server #else haquery.components.button.Client #end;
	inline function innerComponentButton_getter() : #if php haquery.components.button.Server #else haquery.components.button.Client #end
	{
		return cast component.components.get('innerComponentButton');
	}
	
	public var status(status_getter, null) : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end;
	inline function status_getter() : #if php haquery.server.HaqQuery #else haquery.client.HaqQuery #end
	{
		return component.q('#status');
	}

	public function new(component:#if php haquery.server.HaqComponent #else haquery.client.HaqComponent #end) : Void
	{
		this.component = component;
	}
}