package models.autogenerated;

import php.db.ResultSet;
import haquery.server.db.HaqDb;

class UsersManager
{
	function modelByParams(id:Int, login:String, f:String, birthday:Date) : models.Users
	{
		var _obj = new models.Users();
		_obj.id = id;
		_obj.login = login;
		_obj.f = f;
		_obj.birthday = birthday;
		return _obj;
	}

	function modelByRow(d:Dynamic) : models.Users
	{
		var _obj = new models.Users();
		_obj.id = Reflect.field(d, 'id');
		_obj.login = Reflect.field(d, 'login');
		_obj.f = Reflect.field(d, 'f');
		_obj.birthday = Reflect.field(d, 'birthday');
		return _obj;
	}

	public function get(id:Int) : models.Users
	{
		return object('SELECT * FROM `users` WHERE `id` = ' + HaqDb.quote(id));
	}

	public function create(login:String, f:String, birthday:Date) : models.Users
	{
		HaqDb.query('INSERT INTO `users`(`login`, `f`, `birthday`) VALUES (' + HaqDb.quote(login) + ', ' + HaqDb.quote(f) + ', ' + HaqDb.quote(birthday) + ')');
		if (HaqDb.affectedRows() < 1) return null;
		return modelByParams(HaqDb.lastInsertId(), login, f, birthday);
	}

	public function delete(id:Int) : Void
	{
		HaqDb.query('DELETE FROM `users` WHERE `id` = ' + HaqDb.quote(id) + ' LIMIT 1');
	}

	public function all(_order:String=null) : Array<models.Users>
	{
		return objects('SELECT * FROM `users`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function object(sql:String) : models.Users
	{
		var rows : ResultSet = HaqDb.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return modelByRow(rows.next());
	}

	public function objects(sql:String) : Array<models.Users>
	{
		var rows : ResultSet = HaqDb.query(sql);
		var list : Array<models.Users> = [];
		for (row in rows)
		{
			list.push(modelByRow(row));
		}
		return r;
	}

	public function getByLogin(login:String) : models.Users
	{
		return object('SELECT * FROM `users` WHERE `login` = ' + HaqDb.quote(login));
	}
}