package models.autogenerated;

import haquery.server.db.HaqDb;

class Users
{
	public var id : Int
	public var login : String
	public var f : String
	public var birthday : Date

	public function set(login:String, f:String, birthday:Date) : Void
	{
		this.login = login;
		this.f = f;
		this.birthday = birthday;
	}

	public function save() : Void
	{
		HaqDb.query(
			 'UPDATE `users` SET '
				+  '`login` = ' + HaqDb.quote(login)
				+', `f` = ' + HaqDb.quote(f)
				+', `birthday` = ' + HaqDb.quote(birthday)
			+' WHERE `id` = ' + HaqDb.quote(id)
			+' LIMIT 1'
		);
	}
}